import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'Golf Stats',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <main>
          <nav className="p-1 w-full flex justify-evenly bg-blue-500">
            <Link href="/">Home</Link>
            <Link href="/courses">Courses</Link>
          </nav>
          <section className="p-1">{children}</section>
        </main>
      </body>
    </html>
  );
}
